version: "3.8"

services:
  db:
    container_name: menuapp-db-dev
    image: postgres
    environment:
      POSTGRES_USER: menuapp
      POSTGRES_PASSWORD: menuapp
      PGDATA: /data/postgres
    volumes:
      - db-test:/data/postgres
    ports:
      - 5432:5432
    networks:
      - app-network
  dbadmin:
    container_name: menuapp-dbadmin-dev
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: menuapp@pgadmin.org
      PGADMIN_DEFAULT_PASSWORD: menuapp
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - dbadmin-dev:/var/lib/pgadmin
    ports:
      - 5050:80
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-dev:
  dbadmin-dev: